### PR TITLE
Make how plugins are saved better.

### PR DESCRIPTION
**Pull request by itslukej**
https://github.com/ezzybot/ezzybot/issues/19

### CODE REVIEW

**Comment by itslukej** [comment]
Seems to add 52 more issues because of protected class members, anyone know a good work-a-round?

**Comment by itslukej** [comment]
@ezzybot/devs 

Seems to add 52 more issues because of protected class members, anyone know a good work-a-round?

**Comment by Bowserinator** [comment]
Oh that's a lot of issues

**Comment by IndigoTiger** [comment]
[This page](https://www.quantifiedcode.com/knowledge-base/correctness/Avoid%20accessing%20protected%20class%20members%20from%20outside/12Oovuqx) suggests a couple of workarounds (using a `property` decorator or adding the protected member to `__all__`). I think both of these seem to be a PITA but the latter may be less-so.

Aside from the code quality issues, in my opinion, this is definitely an improvement on the code it replaces.

**Comment by itslukej** [comment]
I thought property decorators only work with functions/classes?

**Comment by BWBellairs** [comment]
I'll go through the code today and fix typos and change poor variable names if that's alright?

**Comment by BWBellairs** [comment]
Doing this will allow us to improve the quality of our code and allow us to add new features without running out of variable names

**Pull request merged**
